name: piperswe-cloudflared
title: cloudflared
summary: The command-line client for Cloudflare Tunnel and Cloudflare Access
description: |
  cloudflared is an all-in-one command-line tool containing a client for
  running tunnels connected to the Cloudflare Tunnel service and for accessing
  services hosted behind Cloudflare Access.

  This snap is unofficial. While the author does work for Cloudflare, they do
  not work on the team responsible for cloudflared and this snap was not
  created with that team's blessing. If you wish to use official cloudflared
  binaries, download them from the official Cloudflare website.
issues: https://github.com/cloudflare/cloudflared/issues
source-code: https://github.com/cloudflare/cloudflared
license: Apache-2.0
version: "2022.10.2"
grade: stable
base: core20

confinement: strict

parts:
  cloudflared:
    source-type: git
    source: https://github.com/cloudflare/cloudflared
    source-tag: "2022.10.2"
    build-snaps:
      - go
    plugin: make
    make-parameters:
      - cloudflared
      - VERSION=2022.10.2
      - PACKAGE_MANAGER=snap

apps:
  cloudflared:
    command: usr/bin/cloudflared
    plugs:
      - home
      - network
      - network-bind
